### PR TITLE
import es module

### PR DESCRIPTION
**Pull request by gastonfeng**

### CODE REVIEW

**Comment by noxify** [comment]
Hi,

Thanks for the PR.

What is the benefit from using `import()` ?

Why did you changed it only for one package and not for all?

**Comment by gastonfeng** [comment]
Hi,
in my project:
require() of ES modules is not supported.
so, change require to import is ok.
image-download is a ES module.

**Comment by capsia37** [comment]
Hi,
same here, I think it is probably related to a newer node version

**Comment by capsia37** [comment]
Hi @gastonfeng , have you solved your issue? I think this merge request is still useful if someone needs to use a newer version of node. In my project I need node 14, because previous versions are not supported by the gridsome-plugin-flexsearch

**Pull request merged**
